# Generated by Django 2.1 on 2018-09-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='ut',
            field=models.ForeignKey(on_delete=True, to='app.UserType', to_field='id'),
        ),
    ]
